### ISSUE TITLE
Query string separator

### ISSUE THREAD

**Issue by fedtrainelearning** [catalyst/moodle-tool_crawler#48]
URLs in mdl_tool_crawler_url contain `&amp;` as the query string separator. Should be just a `&`.
This is because line 257 on, /classes/robot/crawler.php should be `$url = $murl->out($escaped=false);`
At least that fixed the issue for me.
Hope this helps.

**Comment by nicoroeser** [comment]
@fedtrainelearning, thanks for your work on this! We have found that a bit more in the code has to be changed to solve the issue. Our pull request #60 fixes this issue.

We have prepared a test in branch https://github.com/nicoroeser/moodle-tool_crawler/tree/uri-escaping-test-issue48 which shows that the pull request is OK, but which is not the proper way to test this: we should not change `require_once` to `require` for `config.php`, and we should also probably not include `url.php` directly into the PHPUnit test.

Creating an automated test is a bit difficult, because the test needs to have the admin user open the page to be tested (in this case, `url.php`) from the web. It seems that the best way to test this is to

1. make the code testable by moving all logic from `url.php` into a dedicated function, and then
2. call this function from `url.php`, and
3. call this function from the testcase, and only test the function, not `url.php`.

We have not yet started any work in this direction, because we wanted to have feedback on the intended direction first, as this suggested way of testing would involve a bigger structural code change to `url.php` (i.e. move almost everything out of it).

If you dislike that way of testing, another possibility would be to use the `curl` functions and make the PHPUnit test query the web server from the outside. But this always requires a running webserver, of course. It seems to be much more difficult. We have started some work on this in branch https://github.com/nicoroeser/moodle-tool_crawler/tree/improve-uri-escaping-test-issue48 (including some notes in a comment, which you could have a look at).

So we would like to seek some advice. What would you think is best?

1. Do not add a test for this code at all, because it is not that trivial,
2. use the test method described above, and not test the output of `url.php`, but from a function that generates the page, or
3. develop a sophisticated test which uses the `curl` functions, but might have further dependencies on the system around the test cases.

Personally, I think I‘d go with option 1 or 2.

**Comment by nicoroeser** [comment]
In addition to this, there must be a proper way to tackle the existing wrong entries in the database. It is not a good idea to try to rewrite them to proper URIs (even though that would probably work relatively well in practice).

So should we flush the database on plugin update? Provide admins with instructions to do so? A UI element for them?

We can _perhaps_ select everything that has `&amp;` in it and only remove that from the database if you like to keep other entries, but I am not sure how the plugin would react if some nodes got missing by that.

Personally, I would recommend to simply drop all entries from the database, either in the update procedure or manually (given as a recommendation to admins).
